"""
Writer Agent

Transforms analysis into a structured, professional research report.
Produces markdown-formatted output ready for presentation.
"""

import json
from datetime import datetime
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage


WRITER_SYSTEM_PROMPT = """You are a professional financial report writer. Your job is to transform analysis into a polished, well-structured research report.

The report should be:
- Professional and objective in tone
- Well-organized with clear sections
- Data-driven with specific numbers cited
- Actionable with clear conclusions

You MUST produce a report in MARKDOWN format with these exact sections:

# [Company Name] Research Report

**Date:** [Current Date]  
**Analyst:** FinAgent AI Research System  
**Rating:** [Bullish/Neutral/Bearish]  
**Financial Health:** [Strong/Moderate/Weak/Critical]

---

## Executive Summary
[3-4 sentence overview of key findings and recommendation]

---

## Company Overview
[Brief description of the company, sector, and market position]

---

## Financial Analysis

### Key Metrics
| Metric | Value |
|--------|-------|
[Table of key financial metrics]

### Financial Health Assessment
[2-3 paragraphs analyzing the financial data]

---

## SWOT Analysis

### Strengths
- [Bullet points]

### Weaknesses
- [Bullet points]

### Opportunities
- [Bullet points]

### Threats
- [Bullet points]

---

## Key Findings
[Numbered list of the most important findings]

---

## Outlook & Recommendation
[2-3 paragraphs on forward-looking analysis and the investment thesis]

---

## Risk Factors
[Bullet points of key risks to monitor]

---

## Conclusion
[Final 2-3 sentence summary]

---

*This report was generated by FinAgent, an AI-powered financial research system. This is not financial advice. Always conduct your own research before making investment decisions.*

---

IMPORTANT: Respond ONLY with the markdown report. Do not wrap it in JSON or code blocks. Just output the raw markdown."""


class WriterAgent:
    """Transforms analysis into a formatted research report."""
    
    def __init__(self, model: str = "gpt-4o-mini"):
        self.llm = ChatOpenAI(
            model=model,
            temperature=0.3  # Some creativity for writing
        )
    
    def write_report(
        self,
        query: str,
        company: str,
        analysis: dict,
        financial_data: dict | None,
        findings: list[dict]
    ) -> dict:
        """
        Generate a formatted research report.
        
        Args:
            query: Original user query
            company: Target company
            analysis: Analysis dict from Analyst
            financial_data: Financial metrics
            findings: Raw findings list
            
        Returns:
            dict with report markdown and metadata
        """
        # Format financial metrics for the prompt
        metrics_text = "No financial data available."
        if financial_data:
            metrics_text = f"""
- Current Price: ${financial_data.get('current_price')}
- Market Cap: ${financial_data.get('market_cap'):,} if financial_data.get('market_cap') else 'N/A'
- P/E Ratio: {financial_data.get('pe_ratio')}
- Forward P/E: {financial_data.get('forward_pe')}
- Profit Margin: {self._format_percent(financial_data.get('profit_margin'))}
- Revenue Growth: {self._format_percent(financial_data.get('revenue_growth'))}
- Debt to Equity: {financial_data.get('debt_to_equity')}
- ROE: {self._format_percent(financial_data.get('roe'))}
- Dividend Yield: {self._format_percent(financial_data.get('dividend_yield'))}
- 52-Week Range: ${financial_data.get('fifty_two_week_low')} - ${financial_data.get('fifty_two_week_high')}
- Sector: {financial_data.get('sector')}
- Industry: {financial_data.get('industry')}
- Company Description: {financial_data.get('description', 'N/A')[:500]}
"""
        
        # Format analysis
        analysis_text = f"""
FINANCIAL HEALTH SCORE: {analysis.get('financial_health_score', 'N/A').upper()}
Rationale: {analysis.get('financial_health_rationale', 'N/A')}

OUTLOOK: {analysis.get('outlook', 'N/A').upper()}
Rationale: {analysis.get('outlook_rationale', 'N/A')}

SUMMARY: {analysis.get('summary', 'N/A')}

KEY FINDINGS:
{chr(10).join(f"- {f}" for f in analysis.get('key_findings', []))}

STRENGTHS:
{chr(10).join(f"- {s}" for s in analysis.get('strengths', []))}

WEAKNESSES:
{chr(10).join(f"- {w}" for w in analysis.get('weaknesses', []))}

OPPORTUNITIES:
{chr(10).join(f"- {o}" for o in analysis.get('opportunities', []))}

THREATS:
{chr(10).join(f"- {t}" for t in analysis.get('threats', []))}
"""
        
        # Format findings
        findings_text = ""
        for finding in findings[:10]:  # Limit to top 10
            findings_text += f"\n[{finding.get('category')}] {finding.get('title')}\n"
            findings_text += f"{finding.get('content')}\n"
            findings_text += f"Source: {finding.get('source')}\n"
        
        messages = [
            SystemMessage(content=WRITER_SYSTEM_PROMPT),
            HumanMessage(content=f"""Write a professional research report based on this analysis.

ORIGINAL QUERY: {query}
COMPANY: {company}
DATE: {datetime.now().strftime("%B %d, %Y")}

FINANCIAL METRICS:
{metrics_text}

ANALYSIS:
{analysis_text}

RESEARCH FINDINGS:
{findings_text}

Generate the complete research report in markdown format.""")
        ]
        
        try:
            response = self.llm.invoke(messages)
            report = response.content
            
            # Clean up if wrapped in code blocks
            if report.startswith("```markdown"):
                report = report[11:]
            if report.startswith("```"):
                report = report[3:]
            if report.endswith("```"):
                report = report[:-3]
            report = report.strip()
            
            return {
                "success": True,
                "report": report,
                "company": company,
                "outlook": analysis.get("outlook"),
                "financial_health": analysis.get("financial_health_score"),
                "generated_at": datetime.now().isoformat()
            }
            
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }
    
    def _format_percent(self, value) -> str:
        """Format a decimal as percentage."""
        if value is None:
            return "N/A"
        if isinstance(value, (int, float)):
            return f"{value * 100:.1f}%"
        return str(value)


# Node function for LangGraph
def writer_node(state: dict) -> dict:
    """
    LangGraph node wrapper for the Writer agent.
    
    Reads: query, company, analysis, financial_data, raw_findings
    Writes: report_draft, current_agent, errors
    """
    writer = WriterAgent()
    
    result = writer.write_report(
        query=state.get("query", ""),
        company=state.get("company", "Unknown"),
        analysis=state.get("analysis", {}),
        financial_data=state.get("financial_data"),
        findings=state.get("raw_findings", [])
    )
    
    if result["success"]:
        return {
            "report_draft": result["report"],
            "current_agent": "writer_complete"
        }
    else:
        return {
            "report_draft": None,
            "current_agent": "writer_failed",
            "errors": [f"Writer error: {result.get('error')}"]
        }


# Test function
if __name__ == "__main__":
    from dotenv import load_dotenv
    load_dotenv()
    
    writer = WriterAgent()
    
    # Simulate analysis from Analyst
    test_analysis = {
        "key_findings": [
            "Goldman Sachs has a market cap of $197 billion and solid profitability metrics",
            "Q4 2024 earnings exceeded analyst expectations",
            "Analysts maintain consensus Buy rating with $580 price target",
            "Strong performance in investment banking and trading divisions",
            "Regulatory scrutiny remains an ongoing concern"
        ],
        "strengths": [
            "Strong profitability with 25% profit margin and 12% ROE",
            "Recent earnings beat demonstrates operational excellence",
            "Leading position in investment banking and trading"
        ],
        "weaknesses": [
            "High debt-to-equity ratio of 2.1 poses leverage risk",
            "Low ROA indicates inefficient asset utilization",
            "Exposure to market volatility in trading operations"
        ],
        "opportunities": [
            "Growing demand for M&A advisory services",
            "Expansion of asset management division",
            "Digital transformation initiatives"
        ],
        "threats": [
            "Basel III endgame capital requirements",
            "Increasing competition from boutique firms",
            "Economic downturn could impact deal flow"
        ],
        "financial_health_score": "moderate",
        "financial_health_rationale": "Goldman shows strong profitability but elevated leverage poses risks in adverse conditions.",
        "outlook": "bullish",
        "outlook_rationale": "Strong earnings momentum and analyst consensus support positive outlook despite regulatory headwinds.",
        "summary": "Goldman Sachs demonstrates strong profitability and favorable analyst outlook with some leverage concerns."
    }
    
    test_financial_data = {
        "company_name": "Goldman Sachs Group Inc.",
        "ticker": "GS",
        "current_price": 505.32,
        "market_cap": 197000000000,
        "pe_ratio": 17.5,
        "forward_pe": 14.2,
        "profit_margin": 0.25,
        "revenue_growth": 0.08,
        "debt_to_equity": 2.1,
        "roe": 0.12,
        "dividend_yield": 0.02,
        "fifty_two_week_high": 612.73,
        "fifty_two_week_low": 389.61,
        "sector": "Financial Services",
        "industry": "Capital Markets",
        "description": "The Goldman Sachs Group, Inc. operates as a global investment banking, securities, and investment management company."
    }
    
    test_findings = [
        {
            "category": "financial_metrics",
            "title": "Strong Profitability Profile",
            "content": "Goldman maintains industry-leading profit margins at 25%",
            "source": "Financial Data"
        },
        {
            "category": "recent_news",
            "title": "Q4 Earnings Beat",
            "content": "Goldman reported EPS above consensus driven by trading revenue",
            "source": "Earnings Report"
        }
    ]
    
    print("=" * 50)
    print("Generating research report...")
    print("=" * 50)
    
    result = writer.write_report(
        query="Analyze Goldman Sachs' financial health and outlook",
        company="Goldman Sachs",
        analysis=test_analysis,
        financial_data=test_financial_data,
        findings=test_findings
    )
    
    if result["success"]:
        print("\nReport generated successfully!")
        print(f"Outlook: {result['outlook']}")
        print(f"Financial Health: {result['financial_health']}")
        print("\n" + "=" * 50)
        print("REPORT PREVIEW (first 2000 chars):")
        print("=" * 50)
        print(result["report"][:2000])
        print("\n... [truncated]")
    else:
        print(f"Error: {result.get('error')}")